### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by ghost** [dumbo-the-developer/GodSpunkySkyblockCore#2]
https://github.com/dumbo-the-developer/GodSpunkySkyblockCore/blob/ee4313eebb89086734f5528441fae2cc00549778/src/main/java/me/godspunky/skyblock/listener/PlayerListener.java#L503

Checking event.getView().getTitle() to see whether your custom inventory is being used is unsafe, as renaming a chest in an anvil allows users to set their own inventory titles. The correct way to check if your custom inventory is involved with an event is by using custom holders, see here: https://docs.papermc.io/paper/dev/custom-inventory-holder

**Comment by dumbo-the-developer** [comment]
The plugin is open for contributions. I abandoned this plugin looking forward for someone who can continue
